# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nota.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(282, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 258, 346))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.namabarang = QtWidgets.QLineEdit(self.widget)
        self.namabarang.setObjectName("namabarang")
        self.gridLayout.addWidget(self.namabarang, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.hargabarang = QtWidgets.QLineEdit(self.widget)
        self.hargabarang.setObjectName("hargabarang")
        self.gridLayout.addWidget(self.hargabarang, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.jumlahbarang = QtWidgets.QLineEdit(self.widget)
        self.jumlahbarang.setObjectName("jumlahbarang")
        self.gridLayout.addWidget(self.jumlahbarang, 2, 1, 1, 1)
        self.menambahbarang = QtWidgets.QPushButton(self.widget)
        self.menambahbarang.setObjectName("menambahbarang")
        self.gridLayout.addWidget(self.menambahbarang, 3, 0, 1, 1)
        self.hapussemuabarang = QtWidgets.QPushButton(self.widget)
        self.hapussemuabarang.setObjectName("hapussemuabarang")
        self.gridLayout.addWidget(self.hapussemuabarang, 3, 1, 1, 1)
        self.listjumlahbarangnamabaranghargatotal = QtWidgets.QListWidget(self.widget)
        self.listjumlahbarangnamabaranghargatotal.setObjectName("listjumlahbarangnamabaranghargatotal")
        self.gridLayout.addWidget(self.listjumlahbarangnamabaranghargatotal, 4, 0, 1, 2)
        self.cetaknota = QtWidgets.QPushButton(self.widget)
        self.cetaknota.setObjectName("cetaknota")
        self.gridLayout.addWidget(self.cetaknota, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nama Barang"))
        self.label_2.setText(_translate("MainWindow", "harga barang"))
        self.label_3.setText(_translate("MainWindow", "jumlah Barang"))
        self.menambahbarang.setText(_translate("MainWindow", "tambah barang"))
        self.hapussemuabarang.setText(_translate("MainWindow", "Hapus Semua"))
        self.cetaknota.setText(_translate("MainWindow", "Cetak Nota"))
