# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day28.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 327)
        self.penampilsuhu = QtWidgets.QLCDNumber(Dialog)
        self.penampilsuhu.setGeometry(QtCore.QRect(200, 60, 101, 81))
        self.penampilsuhu.setObjectName("penampilsuhu")
        self.pengatursuhu = QtWidgets.QDial(Dialog)
        self.pengatursuhu.setGeometry(QtCore.QRect(190, 180, 131, 111))
        self.pengatursuhu.setObjectName("pengatursuhu")
        self.pengaturkecepatanfan = QtWidgets.QSlider(Dialog)
        self.pengaturkecepatanfan.setGeometry(QtCore.QRect(50, 210, 111, 22))
        self.pengaturkecepatanfan.setOrientation(QtCore.Qt.Horizontal)
        self.pengaturkecepatanfan.setObjectName("pengaturkecepatanfan")
        self.penampilkecepatanfan = QtWidgets.QProgressBar(Dialog)
        self.penampilkecepatanfan.setGeometry(QtCore.QRect(50, 140, 118, 23))
        self.penampilkecepatanfan.setProperty("value", 24)
        self.penampilkecepatanfan.setObjectName("penampilkecepatanfan")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 110, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.tombolpower = QtWidgets.QPushButton(Dialog)
        self.tombolpower.setGeometry(QtCore.QRect(30, 20, 91, 41))
        self.tombolpower.setObjectName("tombolpower")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Fan Speed"))
        self.label_2.setText(_translate("Dialog", "C"))
        self.tombolpower.setText(_translate("Dialog", "Power"))
